skydns:
  image: crosbymichael/skydns
  container_name: skydns
  ports:
    - ${DOCKER_BRIDGE_IP}:53:53/udp
    - 18080:8080
  command: -nameserver ${DNS}:53 -domain ${DOMAIN}
  privileged: true

skydock:
  image: crosbymichael/skydock
  container_name: skydock
  links:
    - skydns
  volumes:
    - /var/run/docker.sock:/docker.sock
  command: -ttl 86400 -environment docker -s /docker.sock -domain ${DOMAIN} -name skydns
  privileged: true

dockerui:
  image: dockerui/dockerui
  container_name: dockerui
  ports:
    - 9000:9000
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  privileged: true
  
