skydns:
  image: crosbymichael/skydns
  container_name: skydns
  ports:
    - 53:53/udp
    - 18080:8080
  command: -nameserver ${DNS}:53 -domain ${DOMAIN}
  privileged: true

skydock:
  image: crosbymichael/skydock
  container_name: skydock
  links:
    - skydns
  volumes:
    - /var/run/docker.sock:/docker.sock
  command: -ttl 30 -environment docker -s /docker.sock -domain ${DOCKER_BRIDGE_IP} -name skydns
  privileged: true
